#!/bin/bash
set -euo pipefail

# This script uses wallet private key signing (ADMIN_PRIVATE_KEY).

source "$(dirname "$0")/utils"

# Check if argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <environment>"
    echo "environment: The environment to deploy to (e.g. testnode, testnet-dev, testnet-staging, testnet, mainnet)"
    exit 1
fi

ENVIRONMENT=$1

CHAIN_NAME=$(get_chain_name "$ENVIRONMENT" "settlement-chain")

echo "⧖ Bridging starting broadcaster parameters for $ENVIRONMENT."

ENVIRONMENT=$ENVIRONMENT forge script script/Administration.s.sol:AdministrationScripts --rpc-url "$CHAIN_NAME" --broadcast --slow --sig "bridgeStartingParameters()"

echo "✔ Done bridging starting broadcaster parameters for $ENVIRONMENT."
