#!/bin/bash
set -euo pipefail

script_dir=$(dirname "$(realpath "$0")")
repo_root=$(realpath "${script_dir}/../")
cd "${repo_root}"

source "${script_dir}/lib/common"

case "${1:-default}" in
    "local")
        source dev/lib/default.env
        export environment_file="dev/lib/default.env"
        ;;
    "testnet-playground")
        source dev/lib/testnet-playground.env
        export environment_file="dev/lib/testnet-playground.env"
        ;;
    "testnet-staging")
        source dev/lib/testnet-staging.env
        export environment_file="dev/lib/testnet-staging.env"
        ;;
    *)
        echo "Usage: $0 [local|testnet-playground|testnet-staging]"
        exit 1
        ;;
esac

environment_dir="deployments/${ENVIRONMENT}"
environment_info_file="${environment_dir}/environment.json"

mkdir -p "${environment_dir}"

forge_clean
forge_install
forge_build_contracts
forge_test_contracts
deploy_create3_factory
forge_deploy_script group_message_broadcaster
forge_deploy_script identity_update_broadcaster
forge_deploy_script node_registry
forge_deploy_script rate_registry
environment_info
