#!/bin/bash
set -euo pipefail

echo "⧖ Deploying local contracts."

forge script script/DeployLocal.s.sol:DeployLocalScripts --rpc-url anvil --broadcast --slow --sig 'deployLocal()'

echo "✔ Done deploying local contracts."

./dev/check-local-deployment
