#
# This image is used to generate an anvil state file that can be used to bootstrap an anvil instance.
# It has also to serve as a builder image for repository-wide tooling.
#
ARG GO_VERSION=1.24
ARG FOUNDRY_VERSION=1.0.0
FROM golang:${GO_VERSION}-bookworm AS builder

LABEL maintainer="eng@ephemerahq.com"
LABEL source="https://github.com/xmtp/smart-contracts"
LABEL description="XMTP Network Anvil State Generator"

WORKDIR /build

SHELL ["/bin/bash", "-c"]

RUN apt-get update &&  \
    apt-get install -y curl jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -L https://foundry.paradigm.xyz | bash && \
    source ~/.bashrc && \
    foundryup -i "${FOUNDRY_VERSION}" &&  \
    cp ~/.foundry/bin/* /usr/local/bin

COPY . .

RUN chmod +x ./dev/gen-anvil-state \
    && ./dev/gen-anvil-state

# Cleanup the builder image.
# Instead of using a builder image, remove the build directory, \
# and copy the files to the app directory.
# This way it's not needed to run duplicate steps (apt-get, foundryup, etc)
WORKDIR /app

RUN cp /build/deployments/anvil_localnet/anvil-state.json . \
    && cp /build/deployments/anvil_localnet/anvil-state-info.json . \
    && rm -rf /build
