#!/bin/bash
set -euo pipefail

source "$(dirname "$0")/utils"

# Check if all arguments are provided
if [ $# -ne 2 ]; then
    echo "Usage: $0 <environment> <chain-type>"
    echo "environment: The environment to deploy to (e.g. testnode, testnet-dev, testnet-staging, testnet, mainnet)"
    echo "chain-type: Either 'settlement-chain' or 'app-chain'"
    exit 1
fi

ENVIRONMENT=$1
CHAIN_TYPE=$2

CHAIN_NAME=$(get_chain_name "$ENVIRONMENT" "$CHAIN_TYPE")

# Determine the deployment function based on chain type
if [ "$CHAIN_TYPE" = "settlement-chain" ]; then
    UPDATE_FUNC="migrateSettlementChainProxies()"
else
    UPDATE_FUNC="migrateAppChainProxies()"
fi

echo "⧖ Migrating $CHAIN_TYPE proxies for $ENVIRONMENT on $CHAIN_NAME."

ENVIRONMENT=$ENVIRONMENT forge script script/Administration.s.sol:AdministrationScripts --rpc-url "$CHAIN_NAME" --broadcast --slow --sig "$UPDATE_FUNC"

echo "✔ Done migrating $CHAIN_TYPE proxies for $ENVIRONMENT on $CHAIN_NAME."
