#!/bin/bash
set -euo pipefail

# Check if both arguments are provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <environment>"
    echo "environment: The environment to deploy to (e.g. testnode, testnet-dev, testnet-staging, testnet, mainnet)"
    exit 1
fi

ENVIRONMENT=$1

# Determine CHAIN_NAME based on ENVIRONMENT
if [ "$ENVIRONMENT" = "testnode" ]; then
    CHAIN_NAME="l2_testnode"
elif [ "$ENVIRONMENT" = "mainnet" ]; then
    CHAIN_NAME="base"
else
    # For testnet-dev, testnet-staging, and testnet
    CHAIN_NAME="base_sepolia"
fi

echo "⧖ Setting starting parameters on $ENVIRONMENT."

ENVIRONMENT=$ENVIRONMENT forge script script/Parameters.s.sol:ParameterScripts --rpc-url "$CHAIN_NAME" --broadcast --slow --sig "setStartingParameters()"

echo "✔ Done setting starting parameters on $ENVIRONMENT."
