#!/bin/bash
set -euo pipefail

anvil $@ &

ANVIL_PID=$!

trap "echo 'Caught SIGTERM, forwarding to $ANVIL_PID'; kill -TERM \"$ANVIL_PID\"" SIGTERM
trap "echo 'Caught SIGINT, forwarding to $ANVIL_PID'; kill -INT \"$ANVIL_PID\"" SIGINT

wait "$ANVIL_PID"

ANVIL_EXIT_STATUS=$?

exit "$ANVIL_EXIT_STATUS"
